In [29]:
import pandas as pd
import numpy as np

In [30]:
file =  r"D:\DataEngineering\Final Year Project\processed_data\final_4_modelling_ready_dataset.csv"
df = pd.read_csv(file)
df.iloc[800:805]

,year,player_id,player_name,team,sold_price,sold_price_in_cr,sold_price_in_usd,base_price,base_price_in_cr,base_price_in_usd,...,bbi_wkts,bbi_runs,bbm_wkts,bbm_runs,has_prior_season,is_mega_auction,int_value,is_capped,age_during_auction,overseas2
800,2017,398438.0,Mayank Agarwal,Rising Pune Supergiants,16000000.0,1.6,238000.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,True,False,2018.0,False,26.0,False
801,2017,969381.0,Milind Tandon,Rising Pune Supergiants,1000000.0,0.1,14000.0,1000000.0,0.1,NaN,...,NaN,NaN,NaN,NaN,False,False,NaN,False,NaN,False
802,2017,272450.0,Mitchell Marsh,Rising Pune Supergiants,48000000.0,4.8,716000.0,NaN,NaN,NaN,...,2.0,14.0,2.0,14.0,True,False,2011.0,True,26.0,True
803,2017,26421.0,R Ashwin,Rising Pune Supergiants,75000000.0,7.5,1119000.0,NaN,NaN,NaN,...,4.0,34.0,4.0,34.0,True,False,2010.0,True,31.0,False
804,2017,1064812.0,Rahul Chahar,Rising Pune Supergiants,1000000.0,0.1,14000.0,1000000.0,0.1,NaN,...,NaN,NaN,NaN,NaN,False,False,2019.0,False,18.0,False

In [31]:
new_df = df.copy()
new_df.iloc[800:805]

,year,player_id,player_name,team,sold_price,sold_price_in_cr,sold_price_in_usd,base_price,base_price_in_cr,base_price_in_usd,...,bbi_wkts,bbi_runs,bbm_wkts,bbm_runs,has_prior_season,is_mega_auction,int_value,is_capped,age_during_auction,overseas2
800,2017,398438.0,Mayank Agarwal,Rising Pune Supergiants,16000000.0,1.6,238000.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,True,False,2018.0,False,26.0,False
801,2017,969381.0,Milind Tandon,Rising Pune Supergiants,1000000.0,0.1,14000.0,1000000.0,0.1,NaN,...,NaN,NaN,NaN,NaN,False,False,NaN,False,NaN,False
802,2017,272450.0,Mitchell Marsh,Rising Pune Supergiants,48000000.0,4.8,716000.0,NaN,NaN,NaN,...,2.0,14.0,2.0,14.0,True,False,2011.0,True,26.0,True
803,2017,26421.0,R Ashwin,Rising Pune Supergiants,75000000.0,7.5,1119000.0,NaN,NaN,NaN,...,4.0,34.0,4.0,34.0,True,False,2010.0,True,31.0,False
804,2017,1064812.0,Rahul Chahar,Rising Pune Supergiants,1000000.0,0.1,14000.0,1000000.0,0.1,NaN,...,NaN,NaN,NaN,NaN,False,False,2019.0,False,18.0,False

In [32]:
print(new_df.isnull().sum())

year                     0
player_id               17
player_name              0
team                  1206
sold_price            1236
                      ...
is_mega_auction          0
int_value             1444
is_capped                0
age_during_auction     651
overseas2              493
Length: 68, dtype: int64

In [33]:
# new_df['player_role'].unique()
print(len(new_df['player_role']))

4028

In [34]:
print(new_df.columns)

Index(['year', 'player_id', 'player_name', 'team', 'sold_price',
       'sold_price_in_cr', 'sold_price_in_usd', 'base_price',
       'base_price_in_cr', 'base_price_in_usd', 'purse_spent',
       'purse_spent_in_cr', 'purse_left', 'purse_left_in_cr', 'status',
       'transferred', 'overseas', 'auction_result', 'id_source',
       'prior_season', 'player_name_stats', 'birthdate', 'age', 'nationality',
       'player_role', 'batting_style', 'bowling_style', 'international_career',
       'tournament', 'team_stats', 'matches', 'innings', 'no', 'runs',
       'highestscore', 'batting_average', 'bf', 'strikerate', '100s', '50s',
       '4s', '6s', 'Ct', 'St', 'wickets', 'economy', 'balls', 'bbi', 'bbm',
       'bowl_ave', 'sr', '4w', '5w', '10w', 't20_start', 't20_end',
       'odi_start', 'odi_end', 'bbi_wkts', 'bbi_runs', 'bbm_wkts', 'bbm_runs',
       'has_prior_season', 'is_mega_auction', 'int_value', 'is_capped',
       'age_during_auction', 'overseas2'],
      dtype='str')

In [35]:
new_df['player_name'].isnull().sum()

np.int64(0)

In [36]:
new_df['player_name_stats'].isnull().sum()

np.int64(2098)

In [37]:
print(new_df['tournament'].unique())
print(new_df['prior_season'].unique())
print(new_df['year'].unique())

<StringArray>
[          nan, 'IPL 2007/08',    'IPL 2009', 'IPL 2009/10',    'IPL 2011',
    'IPL 2012',    'IPL 2013',    'IPL 2014',    'IPL 2015',    'IPL 2016',
    'IPL 2017',    'IPL 2018',    'IPL 2019', 'IPL 2020/21',    'IPL 2021',
    'IPL 2022',    'IPL 2023',    'IPL 2024',    'IPL 2025']
Length: 19, dtype: str
[2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
 2021 2022 2023 2024 2025]
[2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021
 2022 2023 2024 2025 2026]

In [39]:
print(new_df['tournament'].count())
print(new_df['has_prior_season'].value_counts())
print(new_df['prior_season'].count())
print(new_df['prior_season'].value_counts())

1930
has_prior_season
False    2098
True     1930
Name: count, dtype: int64
4028
prior_season
2021    330
2024    330
2025    329
2022    316
2017    313
2023    306
2016    298
2018    270
2020    268
2019    254
2015    225
2014    215
2013    178
2010    139
2011     78
2007     77
2012     74
2008     17
2009     11
Name: count, dtype: int64

In [40]:
playing_role_map = {'Bowling Allrounder':'Allrounder',
                    'Batting Allrounder': 'Allrounder',
                    'Allrounder':'Allrounder',
                    'Bowler':'Bowler',
                    'Top order Batter':'Batsman',
                    'Middle order Batter':'Batsman',
                    'Opening Batter':'Batsman',
                    'Batter':'Batsman',
                    'Wicketkeeper Batter':'Batsman',
                    'Wicketkeeper':'Wicketkeeper'}

new_df['mapped_playing_role'] = new_df['player_role'].map(playing_role_map)

In [41]:
# new_df['mapped_playing_role'].unique()
print(len(new_df['mapped_playing_role']))
new_df.iloc[800:805][['player_id','player_name','player_role','mapped_playing_role']]

4028

     player_id     player_name         player_role mapped_playing_role
800   398438.0  Mayank Agarwal              Batter             Batsman
801   969381.0   Milind Tandon                 NaN                 NaN
802   272450.0  Mitchell Marsh          Allrounder          Allrounder
803    26421.0        R Ashwin  Bowling Allrounder          Allrounder
804  1064812.0    Rahul Chahar              Bowler              Bowler

In [ ]:
new_df['batting_style'].unique()

<StringArray>
[nan, 'Right hand Bat', 'Left hand Bat']
Length: 3, dtype: str

In [6]:
new_df['bowling_style'].unique()

<StringArray>
[                                             nan,
                               'Right arm Medium',
                           'Left arm Fast medium',
                          'Right arm Medium fast',
                          'Right arm Fast medium',
                             'Right arm Offbreak',
                                       'Legbreak',
                                'Legbreak Googly',
                                 'Right arm Fast',
                         'Slow Left arm Orthodox',
                           'Left arm Medium fast',
           'Right arm Medium, Right arm Offbreak',
                                'Left arm Medium',
            'Right arm Offbreak, Legbreak Googly',
                                  'Left arm Fast',
                   'Right arm Offbreak, Legbreak',
                            'Left arm Wrist spin',
 'Right arm Medium, Right arm Offbreak, Legbreak',
    'Slow Left arm Orthodox, Left arm Wrist spin',
     'Right arm Offbreak, Slow Left arm Orthodox',
                               'Right arm Bowler']
Length: 21, dtype: str